news:
  types: [ '', 'industry', 'enterprise' ]
  TYPES: [ '', 'GPS行业新闻', 'GPS企业新闻' ]
  bread: '/news/'
  BREAD: 'GPS新闻中心'

gps:
  types: [ '', 'video', 'extend' ]
  TYPES: [ '', '视频监控产品', 'GPS监控产品' ]
  bread: '/gps/'
  BREAD: 'GPS产品展示'

solutions:
  bread: '/solutions/'
  BREAD: 'GPS解决方案'

download:
  types: [ '', 'web', 'pro' ]
  TYPES: [ '', 'GPS网络版', 'GPS专业版' ]
  bread: '/download/'
  BREAD: 'GPS软件下载'

job:
  bread: '/job/'
  BREAD: '职位招聘'

about:
  bread: '/about/'
  BREAD: '关于我们'

contact:
  bread: '/contact/'
  BREAD: '联系我们'

location:
  bread: '/location/'
  BREAD: '人员定位'
